PROCESSERXML: Checker Class Reference
Checker Class Reference
#include <checker.h>
Public Member Functions
Checker ()
~Checker ()
Static Public Member Functions
static bool check (XMLDocument *xml, DTDDocument *dtd)
static bool recursiveCheck (Element *node, std::map< std::string, std::string > *regex_map)
Detailed Description
Description of class Checker
Definition at line 59 of file checker.h.
Constructor & Destructor Documentation
Checker::Checker ()
Definition de la méthode
Parameters
<em>nom parametre description parametre
Constructor
Definition at line 56 of file checker.cpp.
  {
  }
Checker::~Checker ()
Destructor.
Definition at line 63 of file checker.cpp.
  {
   //Nothing to do
  }
Member Function Documentation
bool Checker::check (XMLDocument * xml, DTDDocument * dtd) static
Definition at line 71 of file checker.cpp.
References DTDDocument::generateRegex(), and XMLDocument::getRoot().
  {
         std::map<string,string>* reg=dtd->generateRegex();
         bool result = recursiveCheck(xml->getRoot(),reg);
         reg->clear();
         delete reg;
         return result;
  }
bool Checker::recursiveCheck (Element * node, std::map< std::string, std::string > * regex_map) static
Definition at line 80 of file checker.cpp.
References Element::attributeToString(), Element::childToString(), Element::getContent(), Element::getContent(), and Element::getType().
  {
         list<XMLContent*>::iterator it;
         string childs = node->childToString();
         string attributes = node->attributeToString();
         string type = node->getType();
         boost::regex attributeRegex((*regex_map)["A"+type]);
         boost::regex elementRegex((*regex_map)["E"+type]);
         if( !boost::regex_match(attributes, attributeRegex) )
         {
                 // cout << attributes << " and " <<  (*regex_map)["A"+type] << " do not match" << endl;
                 return false;
         }
         else
         {
                 // cout << attributes << " and " <<  (*regex_map)["A"+type] << " do match" << endl;
         }
         if( !boost::regex_match(childs, elementRegex) )
         {
                 // cout << childs << " and " <<  (*regex_map)["E"+type] << " do not match" << endl;
                 return false;
         }
         else
         {
                 // cout << childs << " and " <<  (*regex_map)["E"+type] << " do match" << endl;
         }
         for( it = node->getContent()->begin() ; it != node->getContent()->end(); it++)
         {
                 if( (*it)->getType().compare("PCDATA") !=  0)
                 {
                         if( !recursiveCheck((Element*)*it, regex_map) )
{
                                 return false;
                         }
                 }
         }
         return true;
  }
The documentation for this class was generated from the following files:
checker.h
checker.cpp