PROCESSERXML: XMLContent Class Reference
XMLContent Class Reference
#include <xmlcontent.h>
Public Member Functions
XMLContent ()
virtual ~XMLContent ()
virtual std::string getType ()
virtual void printXML ()
virtual std::string toString ()
virtual std::list< XMLContent * > getSonList (std::string name)
virtual std::list< XMLContent * > getAllContent (std::string name)
virtual std::string getOpen ()
virtual std::string getClose ()
virtual std::list< XMLContent * > * getContent ()
virtual std::string operator[] (std::string aname)
Detailed Description
La représentation d'un contenu de l'arbre xml.
Description of class 'XMLContent'
Definition at line 56 of file xmlcontent.h.
Constructor & Destructor Documentation
XMLContent::XMLContent ()
Constructor.
Constructor
Definition at line 30 of file xmlcontent.cpp.
  {
         //Nothing to do
  }
XMLContent::~XMLContent () virtual
Destructor
Destructor.
Definition at line 38 of file xmlcontent.cpp.
  {
   //Nothing to do
  }
Member Function Documentation
std::list< XMLContent * > XMLContent::getAllContent (std::string name) virtual
Renvoie une liste vide
Returns
empty list
Reimplemented in Element.
Definition at line 64 of file xmlcontent.cpp.
  {
         std::list<XMLContent*> emptyList;
         return emptyList;
  }
std::string XMLContent::getClose () virtual
Renvoie ""
Returns
""
Reimplemented in Element, PCData, and Misc.
Definition at line 74 of file xmlcontent.cpp.
Referenced by XSLDocument::applyTemplateHandle(), and XSLDocument::handleTemplate().
  {
         std::string empty;
         return empty;
  }
virtual std::list<XMLContent*>* XMLContent::getContent () inline virtual
Renvoie NULL
Returns
NULL
Reimplemented in Element.
Definition at line 120 of file xmlcontent.h.
Referenced by XSLDocument::applyTemplateHandle(), XSLDocument::applyTemplateHandle(), XSLDocument::applyTemplateHandle(), XSLDocument::applyTemplateHandle(), XSLDocument::applyTemplateHandle(), XSLDocument::applyTemplateHandle(), XSLDocument::handleTemplate(), XSLDocument::handleTemplate(), XSLDocument::handleTemplate(), XSLDocument::handleTemplate(), XSLDocument::handleTemplate(), and XSLDocument::handleTemplate().
         {
                 return NULL;
         }
std::string XMLContent::getOpen () virtual
Renvoie ""
Returns
""
Reimplemented in Element, PCData, and Misc.
Definition at line 69 of file xmlcontent.cpp.
Referenced by XSLDocument::applyTemplateHandle(), and XSLDocument::handleTemplate().
  {
         std::string empty;
         return empty;
  }
std::list< XMLContent * > XMLContent::getSonList (std::string name) virtual
Renvoie une liste vide
Returns
empty list
Reimplemented in Element.
Definition at line 58 of file xmlcontent.cpp.
  {
         std::list<XMLContent*> emptyList;
         return emptyList;
  }
std::string XMLContent::getType () virtual
Renvoie le type (et éventuellement l'espace de nom) du contenu
Returns
la chaîne de caractère décrivant le type
Reimplemented in Element, and PCData.
Definition at line 53 of file xmlcontent.cpp.
Referenced by XSLDocument::handleTemplate(), XSLDocument::handleTemplate(), and XSLDocument::handleTemplate().
  {
         return "error";
  }
virtual std::string XMLContent::operator[] (std::string aname) inline virtual
Surcharge de l'operateur [] return ""
Reimplemented in Element.
Definition at line 129 of file xmlcontent.h.
         {
                 return "";
         }
void XMLContent::printXML () virtual
Affiche sur la sortie standard le noeud
Reimplemented in PCData, Element, and Misc.
Definition at line 48 of file xmlcontent.cpp.
  {
         std::cout<<"Error"<<std::endl;
  }
std::string XMLContent::toString () virtual
Renvoie sur en strin l'element ("" dans ce cas car classe abstraite)
Returns
la chaine de caractère
Reimplemented in PCData, Element, and Misc.
Definition at line 80 of file xmlcontent.cpp.
 {
         return "";
 }
The documentation for this class was generated from the following files:
xmlcontent.h
xmlcontent.cpp