PROCESSERXML: XSLDocument Class Reference
XSLDocument Class Reference
#include <xsldocument.h>
Public Member Functions
XSLDocument (XMLDocument *xsl, XMLDocument *xml)
~XSLDocument ()
std::string process ()
std::string getParse ()
Protected Member Functions
std::vector< std::string > split (std::string &chaine, char c)
std::list< XMLContent * > match (std::string match, Element *currentNode)
std::list< XMLContent * > getListContent (std::list< XMLContent * > roots, std::string name)
std::string handleTemplate (XMLContent *node, std::list< XMLContent * > theList)
std::string applyTemplateHandle (XMLContent *node)
Protected Attributes
XMLDocument * mXsl
XMLDocument * mXml
std::map< std::string,
XMLContent * > templates
std::string mParse
Detailed Description
Description of class XSLDocument
Definition at line 58 of file xsldocument.h.
Constructor & Destructor Documentation
XSLDocument::XSLDocument (XMLDocument * xsl, XMLDocument * xml)
Constructor
Definition at line 49 of file xsldocument.cpp.
 {
         mXml=xml;
         mXsl=xsl;
 }
XSLDocument::~XSLDocument ()
Destructor
Destructor.
Definition at line 59 of file xsldocument.cpp.
  {
  }
Member Function Documentation
std::string XSLDocument::applyTemplateHandle (XMLContent * node) protected
Definition at line 298 of file xsldocument.cpp.
References XMLContent::getClose(), XMLContent::getContent(), XMLContent::getContent(), XMLContent::getContent(), XMLContent::getContent(), XMLContent::getContent(), XMLContent::getContent(), and XMLContent::getOpen().
 {
         std::string toReturn;
         std::map<string,XMLContent*>::iterator his=templates.find((node)->getType());
         if(his!= templates.end())
         {
                 std::list<XMLContent*> * otherList= node->getContent();
                 XMLContent * pointer =his->second;
                 for(std::list<XMLContent*>::iterator that=pointer->getContent()->begin();that!=pointer->getContent()->end();that++)
                 {
                         toReturn+=handleTemplate((*that),*otherList);
                 }
         }
         else
         {
                 toReturn+=node->getOpen();
                 if(node->getContent()!=NULL)
                 {
                         for(std::list<XMLContent*>::iterator that=node->getContent()->begin();that!=node->getContent()->end();that++)
{
                                 toReturn+=applyTemplateHandle(*that);
                         }
                 }
                 toReturn+=node->getClose();
         }
         return toReturn;
 }
std::list< XMLContent * > XSLDocument::getListContent (std::list< XMLContent * > roots, std::string name) protected
Definition at line 194 of file xsldocument.cpp.
 {
         std::list<XMLContent*> lisToReturn;
         for(std::list<XMLContent*>::iterator that=roots.begin();that!=roots.end();that++)
         {
                 std::list<XMLContent*> listSons =(*that)->getSonList(name);
                 for(std::list<XMLContent*>::iterator it=listSons.begin();it!=listSons.end();it++)
                 {
                                 lisToReturn.push_back(*it);
                 }
         }
         return lisToReturn;
 }
std::string XSLDocument::getParse ()
You should call process before getting the xml (This method avoids reprocessing the file)
Returns the HTML file
Definition at line 188 of file xsldocument.cpp.
 {
         return mParse;
 }
std::string XSLDocument::handleTemplate (XMLContent * node, std::list< XMLContent * > theList) protected
Definition at line 209 of file xsldocument.cpp.
References XMLContent::getClose(), XMLContent::getContent(), XMLContent::getContent(), XMLContent::getContent(), XMLContent::getContent(), XMLContent::getContent(), XMLContent::getContent(), XMLContent::getOpen(), XMLContent::getType(), XMLContent::getType(), and XMLContent::getType().
 {
         std::string toReturn="";
         if(node->getType()=="xsl:for-each")
         {
                 std::string pathToDisplay=(*node)["select"];
                 std::vector<std::string> table = split(pathToDisplay,'/');
                 std::list<XMLContent*> otherList;
                 otherList=theList;
                 for(int i=0;i!=table.size();i++)
                 {
                         otherList=getListContent(otherList,table[i]);
                 }
                 for(std::list<XMLContent*>::iterator that=otherList.begin();that!=otherList.end();that++)
                 {
                         for(std::list<XMLContent*>::iterator itis=node->getContent()->begin();itis!=node->getContent()->end();itis++)
{
                                 std::list<XMLContent*> togive;
                                 togive.push_back(*that);
                                 toReturn+=handleTemplate((*itis),togive);
                         }
                 }
         }
         else if(node->getType()=="xsl:value-of")
         {
                 std::list<XMLContent*> otherList;
                 std::string pathToDisplay=(*node)["select"];
                 if(pathToDisplay==".")
                 {
                         otherList=theList;
                 }
                 else{
                         std::vector<std::string> table = split(pathToDisplay,'/');
                         otherList=theList;
                         for(int i=0;i!=table.size();i++)
{
                                 otherList=getListContent(otherList,table[i]);
                         }
                 }
                 for(std::list<XMLContent*>::iterator that=otherList.begin();that!=otherList.end();that++)
                 {
                         // (*that)->printXML();
                         toReturn+=(*that)->getOpen();
                         toReturn+=(*that)->getClose();
                 }
         }
         else if(node->getType()=="xsl:apply-templates")
         {
                 if((*node)["select"]!="")
                 {
                         for(std::list<XMLContent*>::iterator that=theList.begin();that!=theList.end();that++)
{
                                 if( (*node)["select"]==(*that)->getType())
{
                                         toReturn+=applyTemplateHandle(*that);
                                 }
                         }
                 }
                 else
                 {
                         for(std::list<XMLContent*>::iterator that=theList.begin();that!=theList.end();that++)
{
                                 toReturn+=applyTemplateHandle(*that);
                         }
                 }
         }
         else
         {
                 toReturn+=(node->getOpen());
                 if((node->getContent()!=NULL) && (node->getContent()->size()>0))
                 {
                         for(std::list<XMLContent*>::iterator that=node->getContent()->begin();that!=node->getContent()->end();that++)
{
                                 toReturn+=handleTemplate((*that),theList);
                         }
                 }
                 toReturn+=(node->getClose());
         }
         return toReturn;
 }
std::list< XMLContent * > XSLDocument::match (std::string match, Element * currentNode) protected
Definition at line 126 of file xsldocument.cpp.
References Element::getAllContent().
 {
         std::list<XMLContent*> listeToReturn;
         if(match[0]=='/')
         {
                 if( match.size()>1)
                 {
                         if (match[1]=='/')
{
                             // We got a //
                                 match[0]=' ';
                                 std::vector<std::string> table = split(match,'/');
                                 std::list<XMLContent*> temp = root->getAllContent(table[1]);
                                 for(int i=2;i!=table.size();i++)
{
                                         temp=getListContent(temp,table[i]);
                                 }
                                 return temp;
                         }
                         else
{
                             // We got a / and some text after
                                 std::vector<std::string> table = split(match,'/');
                                 std::list<XMLContent*> temp;
                                 temp.push_back(root);
                                 for(int i=1;i!=table.size();i++)
{
                                         temp=getListContent(temp,table[i]);
                                 }
                                 return temp;
                         }
                 }
                 else
                 {
                         std::list<XMLContent*> * temp = new std::list<XMLContent*>;
                         temp->push_back(root);
                         XMLContent * rootnode = new Element("","root",new std::list<XMLAttribute*>, temp);
                         std::list<XMLContent*> temp2 ;
                         temp2.push_back(rootnode);
                         return temp2;
                 }
         }
         else if (match[0]=='.')
         {
                 std::list<XMLContent*> temp;
                 temp.push_back(root);
                 return temp;
         }
         else
         {
                 throw NO_MATCH_PARAMETER;
         }
 }
std::string XSLDocument::process ()
Runs the processer
Processes the xml file
Definition at line 84 of file xsldocument.cpp.
References Element::getContent().
 {
         std::list<XMLContent *> theListToHandle;
         std::list<XMLContent *> * theHandlers;
         std::string parseResult="<!DOCTYPE html>";
         Element * root= mXml->getRoot();
         std::list<XMLContent*>::iterator it = mXsl->getRoot()->getContent()->begin();
         for(;it!=mXsl->getRoot()->getContent()->end();it++)
         {
                 // Handling the main template
                 if(((*it)->getType()=="xsl:template"))
                 {
                         theListToHandle= match((**it)["match"],root);
                         theHandlers=(*it)->getContent();
                 }
                 break;
         }
         for(;it!=mXsl->getRoot()->getContent()->end();it++)
         {
                 // Memorising the other templates
                 if(((*it)->getType()=="xsl:template"))
                 {
                         std::string matchString =(**it)["match"];
                         templates[matchString]=(*it);
                 }
         }
         // Launching the interpreter
         for(list<XMLContent*>::iterator that = theHandlers->begin();that!=theHandlers->end();that++)
         {
                 parseResult+=handleTemplate(*that,theListToHandle);
         }
         mParse=parseResult;
         return parseResult;
 }
std::vector< std::string > XSLDocument::split (std::string & chaine, char c) protected
Definition at line 64 of file xsldocument.cpp.
  {
         int size = chaine.size();
         int r = 0;
         vector<std::string> v;
         for (int i = 0; i < size; i++)
         {
                 if (chaine[i] == c)
                 {
                         v.push_back(chaine.substr(r, i - r));
                         r = i + 1;
                 }
         }
         v.push_back(chaine.substr(r, size - r));
         return v;
  }
Field Documentation
std::string XSLDocument::mParse protected
Definition at line 90 of file xsldocument.h.
XMLDocument* XSLDocument::mXml protected
Definition at line 88 of file xsldocument.h.
XMLDocument* XSLDocument::mXsl protected
Definition at line 87 of file xsldocument.h.
std::map<std::string,XMLContent *> XSLDocument::templates protected
Definition at line 89 of file xsldocument.h.
The documentation for this class was generated from the following files:
xsldocument.h
xsldocument.cpp